// Force dynamic rendering so the page can receive a fresh nonce per request
export const dynamic = "force-dynamic";

// Import Next.js headers() so we can read the nonce injected by middleware
import { headers } from "next/headers";

export default async function CspDemoPage() {
  // Read the nonce value that middleware will attach to the incoming request headers
  const headerStore = await headers();
  const nonce = headerStore.get("x-nonce") || "";

  // These are tiny inline snippets that will be used for the hash-based demo.
  // Keep them EXACTLY the same once the SHA-256 hashes have been generated.
  const hashScript = `document.getElementById("hash-script-result").textContent = "Hash-approved inline script executed.";`;
  const hashStyle = `.hash-style-target { border: 3px solid limegreen; padding: 12px; font-weight: bold; }`;

  // Render the dedicated CSP demonstration page container with simple inline layout styling
  // Inline styles are intentionally used here to support the CSP style demonstration sections below
  return (
    <main style={{ padding: "2rem", fontFamily: "Arial, sans-serif" }}>
      {/* Display the title of the CSP demo page */}
      <h1>CSP Demo Lab</h1>
      <p>
        Dummy page intentionally built to demonstrate how CSP blocks or allows
        content based on the response header sent by the frontend.
      </p>
      {/* Visually separate major demo sections for readability */}
      <hr style={{ margin: "2rem 0" }} />
      {/* Section showing the nonce value generated by middleware for this request */}
      <section>
        <h2>1) Nonce value received from middleware</h2>

        {/* Explain how the nonce is attached to both the CSP header and request headers */}
        <p>
          The middleware will generate a fresh nonce, attach it to the CSP
          header, and also pass it into this page through an{" "}
          <code>x-nonce</code> request header.
        </p>

        {/* Display the nonce so to visually verify it exists */}
        <p>
          <strong>Nonce from request:</strong> {nonce || "No nonce found"}
        </p>
      </section>
      {/* Visually separate major demo sections for readability */}
      <hr style={{ margin: "2rem 0" }} />
      {/* Section demonstrating nonce-based inline style allowance */}
      <section>
        <h2>2) Nonce-based inline style</h2>

        {/* Explain why this inline style should only run when nonce matches the CSP */}
        <p>
          If the CSP header includes <code>style-src 'nonce-...'</code> and this{" "}
          <code>{`<style>`}</code> tag uses the same nonce, the browser should
          allow it.
        </p>

        {/* Inject inline CSS that will only be allowed if the nonce matches the CSP */}
        <style
          nonce={nonce}
          dangerouslySetInnerHTML={{
            __html: `
              .nonce-style-box {
                background: #111;
                color: #fff;
                padding: 16px;
                border-radius: 8px;
                margin-top: 12px;
              }
            `,
          }}
        />

        {/* This box visually confirms whether the nonce-approved inline style ran */}
        <div className="nonce-style-box">
          If a dark background & white text appears here, the nonce-based inline
          style was allowed.
        </div>
      </section>
      {/* Visually separate major demo sections for readability */}
      <hr style={{ margin: "2rem 0" }} />
      {/* Section demonstrating nonce-based inline script allowance */}
      <section>
        <h2>3) Nonce-based inline script</h2>

        {/* This text will be modified only if the nonce-approved script executes */}
        <p id="nonce-script-result">
          If this text changes, the nonce-based inline script executed.
        </p>

        {/* Inject inline JS that will only run if the nonce matches the CSP */}
        <script
          nonce={nonce}
          dangerouslySetInnerHTML={{
            __html: `
              const nonceResult = document.getElementById("nonce-script-result");
              if (nonceResult) {
                nonceResult.textContent = "Nonce-approved inline script executed.";
              }
            `,
          }}
        />
      </section>
      {/* Visually separate major demo sections for readability */}
      <hr style={{ margin: "2rem 0" }} />
      {/* Section demonstrating hash-based inline style allowance */}
      <section>
        <h2>4) Hash-based inline style</h2>

        {/* This inline style is trusted via SHA-256 hash rather than nonce */}
        <p>
          This inline style block is here so we can later whitelist it using a
          SHA-256 hash in the CSP header.
        </p>

        {/* Inject the exact inline CSS whose hash is hardcoded in middleware.ts */}
        <style
          dangerouslySetInnerHTML={{
            __html: hashStyle,
          }}
        />

        {/* This box visually confirms whether the hash-approved style ran */}
        <div className="hash-style-target" style={{ marginTop: "12px" }}>
          If this box gets a green border, the hash-approved inline style ran.
        </div>
      </section>
      {/* Visually separate major demo sections for readability */}
      <hr style={{ margin: "2rem 0" }} />
      {/* Section demonstrating hash-based inline script allowance */}
      <section>
        <h2>5) Hash-based inline script</h2>

        {/* This text will change only if the hash-approved inline script executes */}
        <p id="hash-script-result">
          If this text changes, the hash-approved inline script executed.
        </p>

        {/* Inject the exact inline JS whose hash is hardcoded in middleware.ts */}
        <script
          dangerouslySetInnerHTML={{
            __html: hashScript,
          }}
        />
      </section>
      {/* Visually separate major demo sections for readability */}
      <hr style={{ margin: "2rem 0" }} />
      {/* Section demonstrating CSP blocking of disallowed frame sources */}
      <section>
        <h2>6) Intentionally blocked external iframe</h2>

        {/* Explain why this iframe should violate the frame-src directive */}
        <p>
          If the CSP uses <code>frame-src 'self'</code>, the browser should
          block this external iframe and show a CSP violation in DevTools.
        </p>

        {/* Attempt to load an external iframe that should violate frame-src policy */}
        <iframe
          src="http://localhost:3001/evil-csp-demo.html"
          width="600"
          height="220"
          title="Blocked iframe test"
          style={{ border: "1px solid #ccc", marginTop: "12px" }}
        />
      </section>
      {/* Visually separate major demo sections for readability */}
      <hr style={{ margin: "2rem 0" }} />
      {/* Section demonstrating browser-side CSP violation event handling */}
      <section>
        <h2>7) Browser-side CSP violation listener</h2>

        {/* This text will update when the browser fires a securitypolicyviolation event */}
        <p id="violation-result">
          Open DevTools Console too, but this page will also try to display the
          last CSP violation it sees in the browser.
        </p>

        {/* Listen for CSP violation events so violations can be displayed in-page */}
        <script
          nonce={nonce}
          dangerouslySetInnerHTML={{
            __html: `
              document.addEventListener("securitypolicyviolation", (event) => {
                console.log("CSP violation event:", {
                  blockedURI: event.blockedURI,
                  violatedDirective: event.violatedDirective,
                  effectiveDirective: event.effectiveDirective,
                  originalPolicy: event.originalPolicy,
                  disposition: event.disposition,
                  sourceFile: event.sourceFile,
                  lineNumber: event.lineNumber,
                  documentURI: event.documentURI,
                });

                const output = document.getElementById("violation-result");
                if (output) {
                  output.textContent =
                    "Last violation => directive: " +
                    event.violatedDirective +
                    " | blockedURI: " +
                    event.blockedURI +
                    " | disposition: " +
                    event.disposition;
                }
              });
            `,
          }}
        />
      </section>
    </main>
  );
}

//  Live demo walkthrough checklist:
//    - Show the response header in DevTools Network tab.
//    - Show the nonce value rendered on this page.
//    - Show which inline script/style executed.
//    - Show the blocked iframe violation.
//    - Show Console + Network + backend report logs later.
