// This interface defines the structure of a User object.
// In other words, it reflects exactly what a user row
// looks like in the PostgreSQL users table.

export type UserRole = "user" | "admin";

export interface User {
  // id is a UUID generated by PostgreSQL
  id: string;

  // email is a VARCHAR(255) in PostgreSQL
  email: string;

  // password_hash is a TEXT column in PostgreSQL
  password_hash: string;

  // display_name is a VARCHAR(100) column in PostgreSQL
  display_name: string;

  // bio is a TEXT column in PostgreSQL
  bio: string;

  // role can only be "user" or "admin"
  role: UserRole;

  // is_active is a BOOLEAN column in PostgreSQL
  is_active: boolean;

  // created_at and updated_at are TIMESTAMPTZ columns
  created_at: Date;
  updated_at: Date;
}

// Body for creating a new user
export interface CreateUserInterface {
  email: string;
  password: string;
  display_name: string;
  bio?: string;
  role?: UserRole;
  is_active?: boolean;
}

// Body for logging a user in
export interface LoginUserInterface {
  email: string;
  password: string;
}

// Body for updating a user's profile
export interface UpdateUserProfileInterface {
  display_name?: string;
  bio?: string;
}

// Optional shape for returning a user publicly/safely
// without exposing the password hash
export interface PublicUserInterface {
  id: string;
  email: string;
  display_name: string;
  bio: string;
  role: UserRole;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}
